#use python 3.7.2 image as a base to build flask-stack on it (strech means based on Debian 9.0)
FROM python:3.7.2-stretch

#set wor dir of container to /app (/app == container's root)
WORKDIR /app

#copy content from current dir (.) to /app
ADD . /app


RUN apt-get update \
  && apt install -y libgtk-3-0 libgtk-3-dev \
  && apt update \
  && apt install -y libdbus-glib-1-2 \
  && wget -O FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=de" \
  && tar xjf FirefoxSetup.tar.bz2 -C /opt/ \
  && cp -s /opt/firefox/firefox /usr/local/bin/ \
  && cp -s /opt/firefox/firefox /usr/bin/ \
  && wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz \
  && tar -xvzf geckodriver* \
  && chmod +x geckodriver \
  && mv geckodriver /usr/local/bin \
  && cp /usr/local/bin/geckodriver /usr/bin \
  && pip install -r requirements.txt 


CMD ["uwsgi", "app.ini"]
